# Site settings
title: openify.it
name: openify
description: "openify.it brings small and medium businesses into the data era by giving them access to a powerful search-engine and data analysis tools. Proposing simple solutions to solve customers problems and choosing technologies to implement the solutions."
baseurl: ""
favicon: "/assets/images/favicon.png"
url: "http://openify.it"

# Build settings
markdown: kramdown
permalink: pretty
